---

- name: install requirements
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ docker_requirements }}"

- name: add dockers official gpg key
  apt_key:
    url: "{{ docker_gpg_key_url }}"
    id: "{{ docker_gpg_key_fingerprint }}"

- name: add docker package sources
  apt_repository:
    repo: "{{ docker_repository }}"
    filename: docker-ce

- name: install docker
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ docker_packages }}"
