---

- name: gather service facts
  service_facts:

- name: reload iptables
  shell: /sbin/iptables-restore < /etc/iptables/rules.v4

- name: spamhaus-droplist
  systemd:
    name: spamhaus-droplist
    state: restarted
    enabled: yes
  when: "'spamhaus-droplist.service' in ansible_facts.services"

- name: docker
  systemd:
    name: docker
    state: restarted
    enabled: yes

- name: docker-iptables
  systemd:
    name: docker-iptables
    state: restarted
  when: "'docker-iptables.service' in ansible_facts.services"
